---
title: "Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

```{r}
data("instacart")
```


Column {data-width=650}
-----------------------------------------------------------------------

### **Bar Chart** of Order Count by Department

```{r}
instacart |> 
  group_by(department) |> 
  summarize(
    n = n() 
  ) |> 
  arrange(desc(n)) |> 
    mutate(department = fct_reorder(department, n)) |> 
    plot_ly(
    x = ~department, y = ~n, color = ~department,
    type = "bar", colors = "viridis"
  ) |> 
  layout(
    title = "Order Count by Department",
    xaxis = list(title = "Department"),
    yaxis = list(title = "Count of Orders")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### **Histogram** of Order Time by Hour of Day

```{r}
instacart |> 
  select(order_id, order_hour_of_day) |> 
  distinct(order_id, .keep_all = TRUE) |> 
  plot_ly(
      x = ~order_hour_of_day,
      type = "histogram", colors = "viridis"
    ) |> 
  layout(
    title = "Distribution of Order Time by Hour of Day",
    xaxis = list(title = "Order Hour of Day"),
    yaxis = list(title = "Count of Orders")
  )
```

### **Scatter Plot + Line Graph** of Produce Ordered by Day of Week

```{r}
instacart |> 
  filter(department == "produce") |> 
  mutate(
    organic = ifelse(str_detect(product_name, "[Oo]rganic"), 1, 0),
    organic = factor(
        case_match(
          organic,
          0 ~ "Non-Organic",
          1 ~ "Organic"
        ),
        levels = c("Non-Organic", "Organic")
      ),
    order_dow = factor(
        case_match(
          order_dow,
          0 ~ "Sunday",
          1 ~ "Monday",
          2 ~ "Tuesday",
          3 ~ "Wednesday",
          4 ~ "Thursday",
          5 ~ "Friday",
          6 ~ "Saturday"
        ),
        levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
      )
  ) |> 
  group_by(organic, order_dow) |> 
  summarize(
    n = n()
  ) |> 
  plot_ly(
    x = ~order_dow, y = ~n, color = ~organic,
    type = "scatter", mode = "lines+markers"
  ) |> 
  layout(
    title = "Count of Organic vs Non-Organic Produce \nOrdered by Day of Week",
    xaxis = list(title = "Day of Week"),
    yaxis = list(title = "Count of Orders")
  )
```


